title: RexxJS
description: REXX interpreter for JavaScript with cross-application communication
url: https://rexxjs.org
baseurl: ""

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

theme: minima

include:
  - .list-of-public-lib-publishers.csv

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md